services:
  docscanner:
    image: daominhwysi/docscanner:latest
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file:
      - .env
  redis:
    image: redis:latest
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    volumes:
      - redis-data:/data

volumes:
  redis-data: {}  # phải có dòng này
