"""Rename task

Revision ID: cc1f0ebdbeac
Revises: 
Create Date: 2025-08-02 15:44:30.923456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc1f0ebdbeac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('parseDocumentImages', 'documentParsing', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'done', 'failed', 'cancelled', name='taskstatus'), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inferencelog',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('imageUrls', sa.Text(), nullable=True),
    sa.Column('rawOutput', sa.Text(), nullable=False),
    sa.Column('objectKeys', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('objectUrls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('num_input_token', sa.Integer(), nullable=False),
    sa.Column('num_output_token', sa.Integer(), nullable=False),
    sa.Column('page_order', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requestId', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['requestId'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inferencelog')
    op.drop_table('task')
    # ### end Alembic commands ###
